### ISSUE TITLE
Unknown Target CPU 'generic' on Ubuntu

### ISSUE THREAD

**Issue by alec-hoyland** [JuliaInterop/Cxx.jl#354]
`julia> Pkg.build("Cxx")`
INFO: Building Cxx
INFO: Building julia binary build

`julia> using Cxx`
INFO: Precompiling module Cxx.
error: unknown target CPU 'generic'

`signal (11): Segmentation fault
while loading /home/marder/.julia/v0.6/Cxx/src/Cxx.jl, in expression starting on line 172
_ZN5clang7Builtin7Context16InitializeTargetERKNS_10TargetInfoEPS3_ at /home/marder/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so (unknown line)
_ZN5clang12Preprocessor10InitializeERKNS_10TargetInfoEPS2_ at /home/marder/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so (unknown line)
_ZN5clang16CompilerInstance18createPreprocessorENS_19TranslationUnitKindE at /home/marder/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so (unknown line)
finish_clang_init at /home/marder/.julia/v0.6/Cxx/deps/../src/bootstrap.cpp:1470
init_clang_instance at /home/marder/.julia/v0.6/Cxx/deps/../src/bootstrap.cpp:1578
#setup_instance#26 at /home/marder/.julia/v0.6/Cxx/src/initialization.jl:35
unknown function (ip: 0x7f00accf66bb)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
#setup_instance at ./<missing>:0
__init__ at /home/marder/.julia/v0.6/Cxx/src/initialization.jl:401
macro expansion at /home/marder/.julia/v0.6/Cxx/src/Cxx.jl:173 [inlined]
anonymous at ./<missing> (unknown line)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:589
jl_eval_module_expr at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:205
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:480
jl_parse_eval_all at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:873
jl_load at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:616
include_from_node1 at ./loading.jl:569
unknown function (ip: 0x7f00c92ceb1b)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
include at ./sysimg.jl:14
unknown function (ip: 0x7f00c917386b)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:75
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:577
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
anonymous at ./<missing>:2
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:589
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7f00c929839f)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
process_options at ./client.jl:286
_start at ./client.jl:371
unknown function (ip: 0x7f00c92da6e8)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/ui/../src/julia.h:1424 [inlined]
true_main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:127
main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:264
__libc_start_main at /build/glibc-mXZSwJ/glibc-2.24/csu/../csu/libc-start.c:291
unknown function (ip: 0x40170c)
Allocations: 2186438 (Pool: 2185210; Big: 1228); GC: 2`

**Comment by ararslan** [comment]
What's your `versioninfo()`?

**Comment by alec-hoyland** [comment]
@ararslan 

`julia> versioninfo()`
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, generic)

**Comment by Gnimuc** [comment]
Now Cxx master supports an out-of-box installation for x86_64-pc-linux-gnu platform.
