### ISSUE TITLE
Segmentation fault on macOS

### ISSUE THREAD

**Issue by GlenHenshaw** [JuliaInterop/Cxx.jl#387]
julia> using Cxx
    INFO: Recompiling stale cache file /Users/glenhenshaw/.julia/lib/v0.6/Cxx.ji for module Cxx.

    signal (11): Segmentation fault: 11
    while loading no file, in expression starting on line 0
    _ZNK4llvm18IntrusiveRefCntPtrIN5clang10ASTContextEEdeEv at /Users/glenhenshaw/.julia/v0.6/Cxx/deps/usr/lib/libcxxffi.dylib (unknown line)
    _ZNK5clang16CompilerInstance13getASTContextEv at /Users/glenhenshaw/.julia/v0.6/Cxx/deps/usr/lib/libcxxffi.dylib (unknown line)
    tu_decl at /Users/glenhenshaw/.julia/v0.6/Cxx/deps/usr/lib/libcxxffi.dylib (unknown line)

Any help here would be appreciated. Running macOS 10.13.5, with the latest Xcode and command line tools.

**Comment by Ken-B** [comment]
I had the same issue (on latest macOS, julia 0.6.4), but checking out master and rebuilding fixed it for me.

**Comment by VenkatSubramaniam** [comment]
Also facing this issue.

**Comment by VenkatSubramaniam** [comment]
Never mind, I did the same thing. It looks like this commit:  06cfb1f fixes the seg fault, so if you just Pkg.rm("Cxx") then clone and build it, it'll work fine.

**Comment by Gnimuc** [comment]
looks like this has been fixed. if not, feel free to reopen.
