### ISSUE TITLE
"Atom" could not be resolved

### ISSUE THREAD

**Issue by xiongruixu** [JuliaInterop/Cxx.jl#389]
Want to use Atom+Juno in Mac OS, but failed to install Atom in julia:

(v1.0) pkg> add Atom
ERROR: The following package names could not be resolved:
 * Atom (not found in project, manifest or registry)
Please specify by known `name=uuid`.

**Comment by xiongruixu** [comment]
It also happened when 'add GR' and 'add Interact'

**Comment by Gnimuc** [comment]
report to the wrong repo? https://github.com/JunoLab/Atom.jl

**Comment by xiongruixu** [comment]
reported. Thanks
