### ISSUE TITLE
post v1.0 support issue adding package

### ISSUE THREAD

**Issue by joliver92** [JuliaInterop/Cxx.jl#397]
Hi! 

New to Julia. I've been following the development of this package as of v1.0 and saw yesterday support for v1.0   

When using Julia in the shell I do the following: 

(v1.0) pkg> add Cxx
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ROOT [909c4415]:
 ROOT [909c4415] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

Does it take some time for centralised packages to get access to the changes that have been made? 
 
I also tried using Pkg ;   Pkg.Add("Cxx") and had a similar issue 

Jason

**Comment by joliver92** [comment]
No worries, Thanks for getting back to me so soon. I will play around with your suggestions!

**Comment by virtualgraham** [comment]
Unfortunately `add Cxx#master` or cloning this repo does not currently work either. 

> ERROR: LoadError: MethodError: no method matching VersionNumber(::VersionNumber)
> in expression starting at /Users/user/.julia/packages/Cxx/81BGP/deps/build.jl:35

**Comment by Gnimuc** [comment]
you might want to checkout #400 if you're on macOS.

**Comment by DrKrar** [comment]
I had the same problem in windows and Julia 1.1.0

(v1.1) pkg> add Cxx
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Cxx [a0b5b9ef]:
 Cxx [a0b5b9ef] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0-0.1.1, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.2, 0.1.0-0.1.1, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
