### ISSUE TITLE
Support for Julia 1.1

### ISSUE THREAD

**Issue by philoez98** [JuliaInterop/Cxx.jl#410]
As of right now Cxx cannot be used with Julia 1.1.0. It's still a long way to go and might be better to switch back to older Julia versions or is it in the making / coming sometime soon?

Thanks

**Comment by cdsousa** [comment]
Best Cxx version is at the master branch,  and it works very well with 1.1.0 (except maybe in Windows), just try `pkg> add Cxx#master`.

**Comment by philoez98** [comment]
@cdsousa thanks will be using that!
