### ISSUE TITLE
Cxx fails to build for Julia 1.2 on Linux

### ISSUE THREAD

**Issue by horst5000** [JuliaInterop/Cxx.jl#436]
Since Julia 1.2 is officially out by today, I built it from source (no special flags except MARCH=native) and added Cxx resulting in the error below. It seems like there are some path issues with llvm-tblgen, though I'm not sure, if it's a Cxx issue or a Julia issue. Btw. I'm on Ubuntu 18.04.

```
Error: Error building `Cxx`:
│ mkdir -p build/clang-6.0.1/
│ cd build/clang-6.0.1/ && \
│       cmake -G "Unix Makefiles" \
│               -DLLVM_BUILD_LLVM_DYLIB=ON -DCMAKE_BUILD_TYPE=Release \
│               -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_ENABLE_THREADS=OFF \
│                         -DCMAKE_CXX_COMPILER_ARG1="-D_GLIBCXX_USE_CXX11_ABI=1" \
│               -DLLVM_CONFIG=/home/fppx/bin/julia/usr/bin/../tools/llvm-config -DLLVM_TABLEGEN_EXE=/home/fppx/bin/julia/usr/bin/../tools/llvm-tblgen ../../src/clang-6.0.1
│ Not building debug library because corresponding julia DEBUG library does not exist.
│ To build, simply run the build again once the library at
│ /libjulia-debug.so
│ has been built.
│ -- Found LLVM_CONFIG as /home/fppx/bin/julia/usr/tools/llvm-config
│ CMake Error at /home/fppx/bin/julia/usr/lib/cmake/llvm/LLVMExports.cmake:714 (message):
│   The imported target "llvm-tblgen" references the file
│
│      "/workspace/destdir/tools/llvm-tblgen"
│
│   but this file does not exist.  Possible reasons include:
│
│   * The file was deleted, renamed, or moved to another location.
│
│   * An install or uninstall procedure did not complete successfully.
│
│   * The installation package was faulty and contained
│
│      "/home/fppx/bin/julia/usr/lib/cmake/llvm/LLVMExports.cmake"
│
│   but not all the files it references.
│
│ Call Stack (most recent call first):
│   /home/fppx/bin/julia/usr/lib/cmake/llvm/LLVMConfig.cmake:157 (include)
│   CMakeLists.txt:70 (include)
```

**Comment by Gnimuc** [comment]
> I built it from source (no special flags except MARCH=native)

please try to build Julia with `USE_BINARYBUILDER=0`.

**Comment by horst5000** [comment]
> please try to build Julia with `USE_BINARYBUILDER=0`.

Same error...

**Comment by Gnimuc** [comment]
Could you check it again that `USE_BINARYBUILDER=0` takes effect on the build? It should download LLVM source code and build it from scratch which takes about 45min+ on a normal machine.

**Comment by Gnimuc** [comment]
you could also search `USE_BINARYBUILDER` in `Make.inc` and make it hard-coded to 0 to ensure no prebuilt LLVM binaries are used in your build process.

**Comment by horst5000** [comment]
> Could you check it again that `USE_BINARYBUILDER=0` takes effect on the build? It should download LLVM source code and build it from scratch which takes about 45min+ on a normal machine.

Ok, I'll check again. I cleaned using `make distcleanall` and it downloaded the LLVM source, but the build didn't take that long...
Short note: it works using the precompiled Julia binaries for 1.1 and 1.2.

**Comment by Gnimuc** [comment]
`"/workspace/destdir/tools/llvm-tblgen"` this path is the "install" dir in BB2 shard, which implies that Julia was still using prebuilt LLVM binaries.

**Comment by horst5000** [comment]
Thanks, using `USE_BINARYBUILDER=0` did the job. Maybe this should be added to the README, since many people will start to use 1.2 now it's officially released.

**Comment by Nate711** [comment]
Where is the correct place to put ```Make.user```? I put it in the top-level directory of julia, but ran into the same error that @horst5000 had where USE_BINARYBUILDER=0 was not actually active. Thanks!

**Comment by Gnimuc** [comment]
> I put it in the top-level directory of julia, but ran into the same error that @horst5000 had where USE_BINARYBUILDER=0 was not actually active.

you could try https://github.com/JuliaInterop/Cxx.jl/issues/436#issuecomment-522993980 as a workaround.

**Comment by goretkin** [comment]
What is the bug that gives rise to this issue? Since it's possible to use Cxx with a julia binary release, I would expect it's possible to use it with a locally-compiled julia against an LLVM binary release.

**Comment by Gnimuc** [comment]
Not a bug actually. The reason why we now need to set `USE_BINARYBUILDER=0` is that Cxx needs to be built with llvm/clang source code, but in Julia-1.2+ era, we only need to download and use llvm/clang binaries from LLVMBuilder, so Cxx cannot find those llvm/clang source files, which gives rise to the issue.
