### ISSUE TITLE
[Windows] Crash on include

### ISSUE THREAD

**Issue by dourouc05** [JuliaInterop/Cxx.jl#440]
I was evaluating Cxx.jl and I tried to include something basic, actually just iostream. I started a new Julia shell, imported Cxx, switched into the C++ mode, and typed the include. On execution, Julia immediately crashed; the include is not included in my history (i.e. I cannot find it back when starting Julia again, unlike the Cxx import). 

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> import Cxx

C++ > iostream
```

I don't have a Julia debug build, so I'm afraid I cannot provide a stack trace. Here is my Julia version: 

```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Here is the generated `build.jl`: 

```
const BASE_JULIA_BIN="C:\\Users\\Thibaut\\AppData\\Local\\Julia-1.1.1\\bin"
export BASE_JULIA_BIN

const BASE_JULIA_SRC="C:\\Users\\Thibaut\\AppData\\Local\\Julia-1.1.1\\bin\\..\\.."
export BASE_JULIA_SRC

 const IS_BINARYBUILD = true
```

`BASE_JULIA_BIN` actually corresponds to where Julia is installed, but I don't have the sources installed (and thus `BASE_JULIA_SRC` is completely wrong). 

Is there anything I missed?

**Comment by Gnimuc** [comment]
#425

**Comment by dourouc05** [comment]
I had found this issue, but I did not see it was related. I'm closing this, thus.

**Comment by Gnimuc** [comment]
Windows support is still experimental, feel free to file new issues if something goes wrong.
