### ISSUE TITLE
ERROR: LoadError: could not load library "libLLVM-8.0.1"

### ISSUE THREAD

**Issue by ouening** [JuliaInterop/Cxx.jl#467]
OS: Ubuntu18.04
Julia: 1.4.1

When I planed to install Cxx，I encountered error:
```
ERROR: LoadError: could not load library "libLLVM-8.0.1"
│ libLLVM-8.0.1.so: cannot open shared object file: No such file or directory
```
I found that :
```
julia> using Base

julia> Base.lib
libblas_name              libllvm_version_string
liblapack_name            libm_name
libllvm_version           library_threading_enabled
julia> Base.libllvm_version
v"8.0.1"
```
In directory `lib/julia` there has `libLLVM.so` and `libSSVM-8jl.so`，I think the problem is the version of LLVM doesn't satisfy the requirement, as shown in *LINE 23* in `~/.julia/packages/Cxx/1RaOv/deps/build.jl`，can someone tell how to fix it?

**Comment by Gnimuc** [comment]
dup of #464. you could either downgrade Julia to 1.3.x or wait for #465.
