### ISSUE TITLE
Is the project still being developed?

### ISSUE THREAD

**Issue by minghuaw** [JuliaInterop/Cxx.jl#494]
The title is pretty self-explanatory

**Comment by PallHaraldsson** [comment]
I put the last PR in, just doc on 1.3 working, and that was in 2020, and development had been stalled since at least 2019.

There are no open PRs for 2021 yet, but there's some talk of development in issues, e.g.:

https://github.com/JuliaInterop/Cxx.jl/issues/490#issuecomment-900961799

**Comment by Gnimuc** [comment]
Yeah. If everything goes fine, I'm going to continue and try what I wrote in [this comment](https://github.com/JuliaInterop/Cxx.jl/issues/490#issuecomment-900961799) next week.
